In [2]:
import numpy as np

In [12]:
 df=np.array([1,2,3,4,"dfghj",(4+8j)])

In [9]:
type(df)

numpy.ndarray

In [13]:
df

array(['1', '2', '3', '4', 'dfghj', '(4+8j)'], dtype='<U64')

In [15]:
np.array([1,2,23,4.0])#upcasting

array([ 1.,  2., 23.,  4.])

In [17]:
np.array([[4,5],[5,6],[6,7,7]])

C:\Users\Admin\AppData\Local\Temp/ipykernel_20896/380006444.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[4,5],[5,6],[6,7,7]])


array([list([4, 5]), list([5, 6]), list([6, 7, 7])], dtype=object)

In [19]:
np.array([[[4,5],[5,6]],[[6,7],[7,8]]])#3d array

array([[[4, 5],
        [5, 6]],

       [[6, 7],
        [7, 8]]])

In [20]:
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [21]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [26]:
arr=np.array([(1,2),(3,4)],dtype=[("a","<i8"),("b","<i4")])

In [27]:
type(arr[0][0])

numpy.int64

In [28]:
type(arr[0][1])

numpy.int32

In [30]:
arr=np.array([[4,5],[5,6]])   
arr

array([[4, 5],
       [5, 6]])

In [33]:
type(arr[0])

numpy.ndarray

In [32]:
arr[1]

array([5, 6])

In [37]:
a=np.mat(arr)

In [35]:
l=[1,2,3]

In [36]:
np.array(l)

array([1, 2, 3])

In [38]:
np.array(a)

array([[4, 5],
       [5, 6]])

In [39]:
np.asanyarray(a)

matrix([[4, 5],
        [5, 6]])

In [40]:
issubclass(np.matrix,np.ndarray)

True

In [41]:
issubclass(np.ndarray,np.matrix)

False

In [42]:
a

matrix([[4, 5],
        [5, 6]])

In [44]:
arr=a
arr

matrix([[4, 5],
        [5, 6]])

In [46]:
b=np.copy(arr)
b

array([[4, 5],
       [5, 6]])

In [47]:
arr[0][0]=98

In [48]:
a

matrix([[98, 98],
        [ 5,  6]])

In [49]:
b

array([[4, 5],
       [5, 6]])

In [50]:
b.ndim

2

In [51]:
b.size

4

In [52]:
b.shape

(2, 2)

In [54]:
b.dtype

dtype('int32')